spring:
  profiles:
    active:
    - dev
---
server:
  port:2221
spring:
  profile: dev
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
       defaultZone=http://eureka-dev.com:3001/eureka/
---
server:
  port:2222
spring:
  profile: test
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
       defaultZone=http://eureka-dev.com:3001/eureka/
